In [22]:
import tensorflow as ft 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime
import pickle

In [23]:
from tensorflow.keras.models import load_model

model = load_model("model.h5")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [24]:
with open('label_encoder_gender.pkl', 'rb')as file:
    label_encoder_gender=pickle.load(file)

with open('onehot_encoder_geo.pkl', 'rb')as file:
    onehot_encoder_geo=pickle.load(file)

with open('scaler.pkl', 'rb')as file:
    scaler=pickle.load(file)

In [25]:
input_data={
    'CreditScore': 619,
    'Geography':'Germany',
    'Gender':'Female',
    'Age':42,
    'Tenure':2,
    'Balance':0.00,
    'NumOfProducts':1,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':101348.88
}

In [26]:
geo_encoded=onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()
import pandas as pd

d:\PROJECTS\DEEP LEARNING PROJECT\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [27]:
geo_encoded_df=pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
input_data['Gender']=label_encoder_gender.transform([input_data['Gender']])[0]

In [28]:
input_df=pd.DataFrame([input_data])
input_df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,Germany,0,42,2,0.0,1,1,1,101348.88

In [29]:
input_data=pd.concat([input_df.drop('Geography', axis=1), geo_encoded_df], axis=1)

In [30]:
input_scaled=scaler.transform(input_data)

In [31]:
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.0,1,1,1,101348.88,0.0,1.0,0.0

In [35]:
prediction=model.predict(input_scaled)
prediction_proba=prediction[0][0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

In [34]:
prediction_proba

np.float32(0.4561784)